spring:
  application:
    name: user-service
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.gityou.common.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰
