server:
  port: 7051

spring:
  datasource:
    url: jdbc:mysql://192.168.22.137:3306/gityou?characterEncoding=utf-8&userAffectRows=true&serverTimezone=GMT%2B8
    username: gityou
    password: gityou
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7050/eureka
    registry-fetch-interval-seconds: 5

  instance:
    lease-renewal-interval-in-seconds: 3 # 心跳时间
    lease-expiration-duration-in-seconds: 10 # 过期时间

zuul:
  prefix: /api
  routes:
    user-service: /user/**
    repository-service: /repo/**

  retryable: true     # 重试

  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 2000

  sensitive-headers:      # 配置禁止使用的的头信息
  add-host-header: true

repository-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.gityou.gateway.route.RepositoryLoadBalancedRule

# 熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

logging:
  pattern:
    console: '%green(%d{HH:mm:ss}) %highlight(%-5level) %cyan([%30logger{30}]): %msg%n'
    file: '%d{HH:mm:ss} %highlight(%-5level) %green([%-10thread{10}]) %cyan(%50logger{50}) : %msg%n'
