server:
  port: 7072

spring:
  datasource:
    url: jdbc:mysql://192.168.137.1:3306/gityou?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: gityou
    password: gityou
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:7050/eureka
    registry-fetch-interval-seconds: 5  # 每5秒获取一次信息
  instance:
    prefer-ip-address: true   # 使用真实ip地址
    lease-renewal-interval-in-seconds: 5        # 心跳时间
    lease-expiration-duration-in-seconds: 15    # 过期时间


gityou:
  jwt:
    pubKeyPath: /tmp/gityou/rsa.pub     # 公钥地址
    cookieName: user-identity    # cookie的名称

  repositoryPath: /tmp/gityou/repository
