server:
    port: 7072

spring:
    application:
        name: repository-service

    datasource:
        url: jdbc:mysql://192.168.22.137:3306/gityou?characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: gityou
        password: gityou
        driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:7050/eureka
    instance:
        lease-renewal-interval-in-seconds: 5        # 心跳时间
        lease-expiration-duration-in-seconds: 15    # 过期时间

mybatis:
    type-aliases-package: com.gityou.repository.pojo