server:
  port: 7050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7050/eureka
    fetch-registry: false
    register-with-eureka: false

  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 5000

logging:
  pattern:
    console: '%green(%d{HH:mm:ss}) %highlight(%-5level) %cyan([%30logger{30}]): %msg%n'
    file: '%d{HH:mm:ss} %highlight(%-5level) %green([%-10thread{10}]) %cyan(%50logger{50}) : %msg%n'
